accounts/urls.py
from django.urls import path
from .views import *

app_name= 'accounts'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from post.views import post_index, post_detail, post_create,post_update, post_delete

app_name= 'post'
urlpatterns = [
    path('index/', post_index, name='index'),
    path('create/', post_create, name='create'),
    path('<slug:postTitleSlug>/', post_detail, name='detail'),
    path('<slug:postTitleSlug>/update/', post_update, name='update'),
    path('<slug:postTitleSlug>/delete/', post_delete, name='delete'),
]

home/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def home_view(request):
    if request.user.is_authenticated:
        context={
            'isim': 'Enes',
        }
    else:
        context = {
            'isim': 'Misafir',
        }
    return render(request, 'home.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django Dersleri
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    
    
    {% include 'header.html' %}

    {% include 'messages.html' %}
    
    

    {% block body %}
        
    {% endblock body %}
    <script src="{% static 'js/jquery.min.js' %}"></script>        
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    
</body>
</html>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="{% url 'home' %}">Django Dersleri</a>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Ana Sayfa</a>
        </li>
        
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'post:create' %}">Yazı Ekle</a>
          </li>
        {% endif %}          
       
        <li class="nav-item">
          <a class="nav-link" href="{% url 'post:index' %}">Blog</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Hakkımızda</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">İletişim</a>
          </li>

          
          {% if not request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">Üye Ol</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Giriş Yap</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Çıkış Yap</a>
            </li>
          {% endif %}
            
          
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" value="{{ request.GET.q }}" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

templates/home.html
{% extends 'base.html' %}



{% block title %}
    Anasayfa - {{block.super}}
{% endblock title %}
    
    
    {% block body %}
        
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6" style="background-color: aqua;">1. Sutun</div>
                <div class="col-md-6" style="background-color: rgb(31, 189, 128)">2 sIUTIN</div>
            </div>
        </div>

    {% endblock body %}
        

templates/messages.html
{% if messages %}

    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    
    {% endfor %}

{% endif %}